[project]
authors = ["Mira AMM"]
entry = "main.sw"
license = "Apache-2.0"
name = "mira_amm_contract"

[dependencies]
interfaces = { path = "../../libraries/interfaces" }
math = { path = "../../libraries/math" }
utils = { path = "../../libraries/utils" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.1" }
